export const SEARCH = 'SEARCH';
export const UPDATE_SEARCH_STRING = 'UPDATE_SEARCH_STRING';
export const UPDATE_SEARCH_RESULT = 'UPDATE_SEARCH_RESULT';
export const CHECK_PROPERTY_DETAILS = 'CHECK_PROPERTY_DETAILS';
